sonar.organization=g33-moviles-2026-1 
sonar.projectKey=G33-Moviles-2026-1_G33-Flutter-Moviles-2026-1
sonar.projectName=Flutter App
sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**
sonar.dart.coverage.reportPaths=coverage/lcov.info