sonar.projectKey=G33-Moviles-2026-1_G33-Flutter-Moviles-2026-1
sonar.organization=g33-moviles-2026-1

# Nombre del proyecto
sonar.projectName=Mi App Flutter

# Fuentes
sonar.sources=lib

# Exclusiones comunes en Flutter
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**
